---

- name: Clone the openfaas repository
  git:
    repo: "https://github.com/openfaas/faas-netes"
    dest: "/home/{{ user_name }}/openfaas/faas-netes"
  become: yes
  become_user: "{{ user_name }}"

- name: Apply the openfaas files
  shell: "k3s kubectl apply -f /home/{{ user_name }}/openfaas/faas-netes/{{ item }}"
  loop:
    - namespaces.yml
    - yaml_armhf

- name: Install openfaas-cli
  shell: "curl -sSL https://cli.openfaas.com | sh"
  become: yes