---
#- name: Common configuration for all the hosts in the cluster
#  hosts: all
#  become: true
#  roles:
#    - raspi-config
#    - raspian
#    - update
#    - firewall
#    - user
#    - k3s/common/deploy
#
- name: Configure the master
  hosts: master
  become: true
  roles:
    - k3s/master/service

- name: Configure the slaves
  hosts: slave
  become: true
  roles:
    - k3s/slave/service