---

- name: Install ufw
  apt:
    name: ufw

- name: Enable and start ufw
  systemd:
    name: ufw
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Allow connections
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 8472
    - 22

- name: Allow connections for the master
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 6443
    - 31111
    - 31112
  when: '"master" in group_names'

- name: Limit connection attempts on ssh
  ufw:
    rule: limit
    port: ssh

- name: Restart ufw
  systemd:
    name: ufw
    daemon_reload: yes
    state: restarted