---

- name: Deploy k3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and start k3s
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait until the token file is created
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 60

- name: Read token from the master configuration
  become: true
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Save the master token
  set_fact:
    master_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"